export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'
export const FETCH_DATA_LOADING = 'FETCH_DATA_LOADING'
export const FETCH_CRYPTO = 'FETCH_CRYPTO'
export const FETCH_CRYPTO_SUCCESS = 'FETCH_CRYPTO_SUCCESS'
export const FETCH_CRYPTO_FAIL = 'FETCH_CRYPTO_FAIL'
export const FETCH_CRYPTO_LOADING = 'FETCH_CRYPTO_LOADING'


